### ISSUE TITLE
since EDDB is closed Cargo Manifest not working anymore

### ISSUE THREAD

**Issue by Zenchina** [RemainNA/cargo-manifest#9]
Exactly as I wrote above. Simply plugin doesn't even exist in listed plugins in EDMC

**Comment by RemainNA** [comment]
Since I don't know of any replacement API for EDDB I will likely update the plugin and remove all of that functionality, with the plan to add it in later if another API becomes available.

**Comment by Elathiel-gh** [comment]
@RemainNA does this help?
https://inara.cz/elite/inara-api/

**Comment by RemainNA** [comment]
Apologies for not having an update out, I haven't had the time to work on this yet.

It appears to me that the Inara API doesn't work as a replacement for EDDB in this use case since it doesn't report commodity buy/sell value data.  If I have missed that somewhere in the documentation please point it out to me as I would love to be able to use it.

From the searches I have done it looks like [EDPN](https://github.com/ed-pilots-network) is aiming to be a replacement for EDDB, but it's still early in development.  Hopefully it can be used for this soon.

Since this weekend is a long weekend I will try to release the simplified version that doesn't rely on any external API.  Once there is an API that provides the necessary data I will work to add those features back in, hopefully in a more stable way.

**Comment by Elathiel-gh** [comment]
Sorry, my bad.

**Comment by RemainNA** [comment]
Not a problem! I appreciate you looking for alternatives

**Comment by spansh** [comment]
https://spansh.co.uk/dumps

https://downloads.spansh.co.uk/galaxy_stations.json.gz would be the smallest file there containing all market data

Although if you simply need values for a particular station you can get https://spansh.co.uk/api/station/<market_id>.

If you're looking for min/max values for commodities: https://spansh.co.uk/api/stations/field_values/market

Though that information lags behind by roughly 24-48 hours

**Comment by padrim** [comment]
Hi, just wondering if an update for at least the simplified version without market data will be available any time soon. The market data isn't important to me, but being able to look over at ECMC and see current cargo was really useful for at least a few of us. Thanks in advance!

**Comment by RemainNA** [comment]
New version out ([v3.0.0](https://github.com/RemainNA/cargo-manifest/releases/tag/v3.0.0)) which removes EDDB features, and hopefully serves as a stable version moving forward.  As other APIs are worked on I will look to re-introduce similar functionality without introducing major failure points.

**Comment by ultimatespirit** [comment]
With regards to alternative APIs, it seems that https://github.com/iaincollins/ardent-api should provide the relevant trade data via direct APIs (that's the github documentation for the API, the actual website is https://ardent-industry.com with the `api.` prefix for its API.

It even provides bubble / colonia specific "reports" that exclude fleet carrier data for a more stable estimator on a commodity's price at stations in those regions: https://api.ardent-industry.com/v1/commodities/core-systems-1000 (replace `core` with `colonia` for colonia). That could be an interesting data source perhaps.
